name: Idea_Decoder
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - colorama=0.4.6
  - comm=0.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - ffmpeg=7.0.1
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - packaging=24.2
  - parso=0.8.4
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - pyzmq=26.2.0
  - setuptools=75.8.0
  - six=1.17.0
  - sox=14.4.2
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.16
    - aiosignal==1.3.2
    - alembic==1.15.2
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.9.0
    - asteroid-filterbanks==0.4.0
    - attrs==25.3.0
    - audioread==3.0.1
    - certifi==2025.1.31
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - click==8.1.8
    - colorlog==6.9.0
    - contourpy==1.3.1
    - cycler==0.12.1
    - datasets==3.5.0
    - dill==0.3.8
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - einops==0.8.1
    - evaluate==0.4.3
    - filelock==3.18.0
    - fonttools==4.57.0
    - frozenlist==1.5.0
    - fsspec==2024.12.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - greenlet==3.1.1
    - gtts==2.5.4
    - h11==0.14.0
    - httpcore==1.0.8
    - httpx==0.28.1
    - huggingface-hub==0.30.2
    - hyperpyyaml==1.2.2
    - idna==3.10
    - imageio==2.37.0
    - imageio-ffmpeg==0.5.1
    - jinja2==3.1.6
    - jiter==0.9.0
    - jiwer==3.1.0
    - joblib==1.4.2
    - julius==0.2.7
    - kiwisolver==1.4.8
    - lazy-loader==0.4
    - librosa==0.11.0
    - lightning==2.5.1
    - lightning-utilities==0.14.3
    - llvmlite==0.44.0
    - mako==1.3.10
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.1
    - mdurl==0.1.2
    - more-itertools==10.6.0
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multidict==6.4.3
    - multiprocess==0.70.16
    - networkx==3.4.2
    - numba==0.61.2
    - numpy==2.2.4
    - omegaconf==2.3.0
    - openai==1.73.0
    - openai-whisper==20240930
    - optuna==4.3.0
    - pandas==2.2.3
    - pillow==11.2.1
    - pooch==1.8.2
    - primepy==1.3
    - propcache==0.3.1
    - protobuf==5.29.4
    - psutil==7.0.0
    - pyannote-audio==3.3.2
    - pyannote-core==5.0.0
    - pyannote-database==5.1.3
    - pyannote-metrics==3.2.1
    - pyannote-pipeline==3.0.1
    - pyarrow==19.0.1
    - pycparser==2.22
    - pydantic==2.11.3
    - pydantic-core==2.33.1
    - pydub==0.25.1
    - pyparsing==3.2.3
    - pytorch-lightning==2.5.1
    - pytorch-metric-learning==2.8.1
    - pytz==2025.2
    - pyworld==0.3.5
    - pyyaml==6.0.2
    - rapidfuzz==3.13.0
    - regex==2024.11.6
    - requests==2.32.3
    - rich==14.0.0
    - ruamel-yaml==0.18.10
    - ruamel-yaml-clib==0.2.12
    - safetensors==0.5.3
    - scikit-image==0.25.2
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - semver==3.0.4
    - sentencepiece==0.2.0
    - sentry-sdk==2.25.1
    - setproctitle==1.3.5
    - shellingham==1.5.4
    - smmap==5.0.2
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - soundfile==0.13.1
    - soxr==0.5.0.post1
    - speechbrain==1.0.3
    - sqlalchemy==2.0.40
    - sympy==1.13.1
    - tabulate==0.9.0
    - tensorboardx==2.6.2.2
    - threadpoolctl==3.6.0
    - tifffile==2025.3.30
    - tiktoken==0.9.0
    - tokenizers==0.21.1
    - torch==2.5.1
    - torch-audiomentations==0.12.0
    - torch-pitch-shift==1.2.5
    - torchaudio==2.5.1
    - torchmetrics==1.7.1
    - tqdm==4.67.1
    - transformers==4.48.2
    - typer==0.15.2
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - ufal-morphodita==1.11.2.1
    - urllib3==2.4.0
    - wandb==0.19.9
    - websockets==15.0.1
    - xxhash==3.5.0
    - yarl==1.19.0
